### ISSUE TITLE
Folder Picker

### ISSUE THREAD

**Issue by gbaumgart** [gbaumgart/claycenter#4]
i implemented drives as follows : 

![image](https://cloud.githubusercontent.com/assets/1205100/18517464/aa5b23aa-7a9c-11e6-8993-ec2c9baedc8c.png)

whereby everything works like the IDE's file widget:

![image](https://cloud.githubusercontent.com/assets/1205100/18517514/dd3810d0-7a9c-11e6-918a-41c39fa16ebd.png)

still have to do the picker itself and i guess i will display it the same way as in the IDE (see F5 -> Copy to dialog)

**Comment by gbaumgart** [comment]
did only file listing, no other think like upload, copy, delete ,....

**Comment by MediaMerge** [comment]
fine. none of that needed.

**Comment by gbaumgart** [comment]
ok, done. i placed it in "ClayGuenter/AXFile.dhtml"

![image](https://cloud.githubusercontent.com/assets/1205100/18555229/6719283c-7b67-11e6-8082-ac5bb1ed3e1e.png)

we will have to merge this manually in your scene. Run commit.bat in your Control-Freak user directory to send me your last changes, i can add it to your scene from here too.

g
